Fix errors due to using CFLAGS -Wall -Werror
vmod_cookie.c: In function 'vmod_parse':
vmod_cookie.c:81:27: error: unused variable 'key' [-Werror=unused-variable]